На ветке master
Изменения, которые не в индексе для коммита:
  (используйте «git add <файл>…», чтобы добавить файл в индекс)
  (используйте «git checkout -- <файл>…», чтобы отменить изменения
   в рабочем каталоге)

	изменено:      application/plugins/freelancer/frontend/skin/default/components/admin/list.tpl

Неотслеживаемые файлы:
  (используйте «git add <файл>…», чтобы добавить в то, что будет включено в коммит)

	.htaccess
	Readme.EN.txt
	Readme.RU.txt
	application.tar.gz
	application/classes/
	application/config/.htaccess
	application/config/config.local.out.php
	application/config/config.local.php.dist
	application/config/config.php
	application/config/config.production.php.dist
	application/config/config.testing.php.dist
	application/config/jevix.php
	application/config/modules/
	application/config/plugins/
	application/frontend/.htaccess
	application/frontend/components/
	application/frontend/i18n/
	application/frontend/skin/synio/
	application/helper.php
	application/include/
	application/install2/
	application/libs/
	application/logs/
	application/plugins/.gitignore
	application/plugins/admin/
	application/plugins/docs/
	application/plugins/freelancer.tar.gz
	application/plugins/plugins.dat
	application/plugins/robokassa.tar.gz
	application/plugins/smsc/
	application/plugins/ydirect.tar.gz
	application/profimaster.sql
	application/tmp/
	application/utilities/
	bootstrap/
	framework/
	git.st
	gpl-2.0.txt
	index.php
	nbproject/
	profimaster.sql
	profimaster.tar.gz
	robots.txt
	uploads/

нет изменений добавленных для коммита
(используйте «git add» и/или «git commit -a»)
